<?php

/**
 * This is the model base class for the table "post".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Post".
 *
 * Columns in table "post" available as properties of the model,
 * followed by relations of table "post" available as properties of the model.
 *
 * @property string $id
 * @property string $friend
 * @property string $category
 * @property string $seen
 * @property string $not_seen
 *
 * @property Category $category0
 * @property Friend $friend0
 */
abstract class BasePost extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'post';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Post|Posts', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('friend, category, seen, not_seen', 'required'),
			array('friend, category, seen, not_seen', 'length', 'max'=>20),
			array('id, friend, category, seen, not_seen', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'category0' => array(self::BELONGS_TO, 'Category', 'category'),
			'friend0' => array(self::BELONGS_TO, 'Friend', 'friend'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'friend' => null,
			'category' => null,
			'seen' => Yii::t('app', 'Seen'),
			'not_seen' => Yii::t('app', 'Not Seen'),
			'category0' => null,
			'friend0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('friend', $this->friend);
		$criteria->compare('category', $this->category);
		$criteria->compare('seen', $this->seen, true);
		$criteria->compare('not_seen', $this->not_seen, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}